### ISSUE TITLE
osdlyrics doesn't detect media players

### ISSUE THREAD

**Issue by ItachiUchiha91** [PedroHLC/osdlyrics#40]
Hi, I install osdlyrics, but at the startup it says "there is no supported player running" (I use vlc, lollypop and rhythmbox). So I select one of them but osdlyrics doesn't recognize the tracks I playing. 
While installing osdlyrics from the community repository (arch linux) it recognize the tracks I play, but it can't find the lyrics as it doesn't use viewlyrics but only ttplayer and xiaomi. 

**EDIT** I have just installed the legacy-dev and works fine!

**Comment by tnga** [comment]
Hi, for the lastest version, **viewlyrics** have to be manually enable by the user. osdlyrics only provide for now, support for tracks that are tagged. So if your tracks come from particular site that modify track's metadata, it will probably occur to an empty result for lyric searching process even if it's available ; then you have to manually address the lyric. 

However, due to time to time modifications, actual dev branch can be unstable.
